# pyproject.toml
[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "event-booking-api"
version = "0.1.0"
requires-python = ">=3.14"

# All dependencies are in requirements/
dependencies = []

[project.scripts]
builder = "builder.__main__:main"

[tool.setuptools.packages.find]
include = ["app*", "builder*"]
