### Revision order ###
# Revisions are applied in this exact order, each one chained to the one before it
# The first one in the tuple is chained after inital auto generated revision, 
# therefore it recieve auto-generated by Alembic revision ID in down_revions
REVISIONS = (
    "add_updated_at_triggers.py",
    )
