"""Initial database structure

Revision ID: 48c08f9d6c04
Revises: 
Create Date: 2026-08-25 20:57:07.963300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.db.types

# revision identifiers, used by Alembic.
revision: str = '48c08f9d6c04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('hashed_password', app.db.types.HashedPasswordType(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'organizer', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ends_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("NOT (status = 'draft' AND public = true)", name='ck_events_draft_not_public'),
    sa.CheckConstraint("status IN ('draft', 'active', 'finished', 'cancelled')", name='ck_events_status'),
    sa.CheckConstraint('capacity > 0', name='ck_events_capacity_positive'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_events_ends_after_starts'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_owner_id', 'events', ['owner_id'], unique=False)
    op.create_index('ix_events_starts_at', 'events', ['starts_at'], unique=False)
    op.create_index('ix_events_status', 'events', ['status'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'confirmed'"), nullable=False),
    sa.Column('ticket_amount', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('confirmed', 'cancelled')", name='ck_bookings_status'),
    sa.CheckConstraint('ticket_amount > 0', name='ck_bookings_ticket_amount_positive'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookings_event_confirmed', 'bookings', ['event_id', 'ticket_amount'], unique=False, postgresql_where=sa.text("status = 'confirmed'"))
    op.create_index('ix_bookings_event_id', 'bookings', ['event_id'], unique=False)
    op.create_index('ix_bookings_user_id', 'bookings', ['user_id'], unique=False)
    op.create_index('uq_bookings_active', 'bookings', ['user_id', 'event_id'], unique=True, postgresql_where=sa.text("status = 'confirmed'"))

    op.execute("""
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """)

    op.execute("""
        CREATE TRIGGER set_users_updated_at
        BEFORE UPDATE ON users
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();
        """)

    op.execute("""
        CREATE TRIGGER set_events_updated_at
        BEFORE UPDATE ON events
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();
        """)

    op.execute("""
        CREATE TRIGGER set_bookings_updated_at
        BEFORE UPDATE ON bookings
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS set_bookings_updated_at ON bookings;")
    op.execute("DROP TRIGGER IF EXISTS set_events_updated_at ON events;")
    op.execute("DROP TRIGGER IF EXISTS set_users_updated_at ON users;")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at();")

    op.drop_index('uq_bookings_active', table_name='bookings', postgresql_where=sa.text("status = 'confirmed'"))
    op.drop_index('ix_bookings_user_id', table_name='bookings')
    op.drop_index('ix_bookings_event_id', table_name='bookings')
    op.drop_index('ix_bookings_event_confirmed', table_name='bookings', postgresql_where=sa.text("status = 'confirmed'"))
    op.drop_table('bookings')
    op.drop_index('ix_events_status', table_name='events')
    op.drop_index('ix_events_starts_at', table_name='events')
    op.drop_index('ix_events_owner_id', table_name='events')
    op.drop_table('events')
    op.drop_table('users')
    # ### end Alembic commands ###
