from ..config import ALEMBIC_VERSIONS_DIR, REVISIONS_DIR, REVISIONS
from ..system import CommandFailed, run

# down_revision placeholder every static revision carries, 
# filled in when the revision is copied into alembic/versions
PLACEHOLDER = "__PREVIOUS__"

def copy_static() -> None:
    """
    Copies the static revisions on top of the generated one.

    Every static revision carries its fixed revision id and a placeholder __PREVIOUS__ 
    in down_revision where its parent revision ID will be assigned. The parent of the 
    first static revision is a new autogenerated inital revision ID. Each next static 
    revision have ID of the previous static one.
    """
    previous = _generated_revision()

    for name in REVISIONS:
        content = (REVISIONS_DIR / name).read_text()
        content = content.replace(PLACEHOLDER, previous)

        (ALEMBIC_VERSIONS_DIR / name).write_text(content)

        # After the first iteration `previous` ID is replaced with
        # the ID of a static revision, otherwise it would carry
        # generated revision ID and alembic revision chain will be broken
        previous = _declared_revision(content)


def _generated_revision() -> str:
    """
    Returns the id of the initial revision autogenerate has just produced.

    Uses alembic to ask for the revision ID, since the file name is
    generated as well.
    """
    heads = run(["alembic", "heads"], capture=True).split()

    if not heads:
        raise CommandFailed(
            "Alembic reports no revision after autogenerate."
        )

    return heads[0]


def _declared_revision(content: str) -> str:
    """
    Reads the revision ID a static revision declares for itself.

    down_revision never matches, because the line has to start with the
    word revision.
    """
    for line in content.splitlines():
        if line.startswith("revision"):
            return line.split("=")[1].strip().strip("\"'")

    raise CommandFailed(
        "A static revision has no own revision ID assigned. Please assigin it."
        )
