import argparse
import shutil

from . import env_file, secrets
from .docker import compose, running_services, volumes
from .environment import LOCAL, REPOSITORY
from .output import bold, green, red
from .revisions import REVISIONS, REVISIONS_DIR
from .shell import CommandFailed, run

VERSIONS_DIR = REPOSITORY / "alembic" / "versions"
PLACEHOLDER = "__PREVIOUS__"


def rebuild_schema(args: argparse.Namespace) -> None:
    """
    Regenerates the Alembic initial revision from the database models, 
    then re-applies the static revisions from builder/revisions.

    Runs using the local enviornment, because new revisions must be
    included in repository.

    The database must be empty, since Alembic autogenerate compares the 
    models with current db content, so a remaining volume from previous runs 
    would produce an empty migration instead of the whole inital schema.

    Nothing is left behind after a succesfull run. The result is only a set of new 
    revisions, that are verified by applying 'alembic upgrade head' and 
    'alembic down base'.
    """
    existing = _existing()

    if existing and not _confirmed(existing):
        print("Operation aborted, nothing was removed.")
        return

    _remove_existing()

    env_file.write(LOCAL)
    secrets.create(LOCAL)

    try:
        compose(LOCAL, "up", "-d", "--wait")

        run([
            "alembic", "revision", "--autogenerate",
            "-m", "Initial database structure",
        ])

        _copy_static_revisions()

        # Test both directions, upgrade and downgrade
        run(["alembic", "upgrade", "head"])
        run(["alembic", "downgrade", "base"])

    finally:
        # Removes all elements this command created, no matter the result.
        compose(LOCAL, "down", "-v")
        _remove_directory(LOCAL.SECRET_DIR)
        _remove_directory(LOCAL.LOG_DIR)

    print()
    for path in sorted(VERSIONS_DIR.glob("*.py")):
        print(green(f"Created {path.relative_to(REPOSITORY)}"))


### Helpers ###
def _existing() -> list[str]:
    """
    Returns list of elements the rebuild-schema will destroy, used for 
    user confirmation.
    """
    items = []

    if running_services(LOCAL):
        items.append("the running local containers")

    if volumes(LOCAL):
        items.append("the local database volume, with all its data")

    for path in (LOCAL.SECRET_DIR, LOCAL.LOG_DIR):
        if path.is_dir():
            items.append(str(path))

    revisions = sorted(VERSIONS_DIR.glob("*.py"))

    if revisions:
        items.append(f"{len(revisions)} revision file(s) in alembic/versions")

    return items


def _confirmed(existing: list[str]) -> bool:
    print(red("This removes, permanently:"))

    for item in existing:
        print(f"  - {item}")

    return input("Continue? [y/N] ").strip().lower() == "y"


def _remove_existing() -> None:
    """
    Remove all the elements of the local enviornment and current alembic 
    revions in repo. 
    """
    compose(LOCAL, "down", "-v")

    _remove_directory(LOCAL.SECRET_DIR)
    _remove_directory(LOCAL.LOG_DIR)

    for path in VERSIONS_DIR.glob("*.py"):
        path.unlink()
        print(red(f"Removed {path.relative_to(REPOSITORY)}."))


def _remove_directory(path) -> None:
    """
    The local enviornment keeps everything inside the repository no
    root needs to involved to delete.
    """
    shutil.rmtree(path, ignore_errors=True)


def _copy_static_revisions() -> None:
    """
    Copies the static revisions on top of the generated one.

    Every static revision carries its fixed revision id and a placeholder __PREVIOUS__ 
    in down_revision where its parent revision ID will be assigned. The parent of the 
    first static revision is a new autogenerated inital revision ID. Each next static 
    revision have ID of the previous static one.
    """
    previous = _generated_revision()

    for name in REVISIONS:
        content = (REVISIONS_DIR / name).read_text()
        content = content.replace(PLACEHOLDER, previous)

        (VERSIONS_DIR / name).write_text(content)

        # After the first iteration `previous` ID is replaced with
        # the ID of a static revision, otherwise it would carry
        # generated revision ID and alembic revision chain will be broken
        previous = _declared_revision(content)


def _generated_revision() -> str:
    """
    Returns the id of the initial revision autogenerate has just produced.

    Uses alembic to ask for the revision ID.
    """
    return run(["alembic", "heads"], capture=True).split()[0]


def _declared_revision(content: str) -> str:
    """
    Reads the revision ID from a static revision.
    """
    for line in content.splitlines():
        if line.startswith("revision"):
            return line.split("=")[1].strip().strip("\"'")

    raise CommandFailed(
        "A static revision has no own revision ID assigned. Please assigin it."
        )
